### ISSUE TITLE
Numerous errors when launching 'ledger-live-desktop' app with pnpm 

### ISSUE THREAD

**Issue by who-biz** [who-biz/ledger-live#1]
Follow build steps in ``README.md`, then attempt to launch app in development mode with `pnpm desktop start`.

Following runtime errors result:

```The following dependencies are imported but could not be resolved:

  react-native-aes-crypto (imported by $HOME/ledger-live/libs/ledger-live-common/lib-es/families/mimblewimble_coin/api/crypto.js)

Are they installed?
[BABEL] Note: The code generator has deoptimised the styling of $HOME/ledger-live/libs/ui/packages/icons/react/Flags/Do.js as it exceeds the max of 500KB.
✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/secp256k1-zkp-react". The package may have incorrect main/module/exports specified in its package.json.

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21:
      1327 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
    at resolvePackageEntry (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34097:5)
    at tryNodeResolve (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
    at Context.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33598:28)
    at Object.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40156:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62481:21
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34415:34
    at async requestCallbacks.on-resolve ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:22)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:20:
      1251 │       let promise = setup({
           ╵                     ^

    at setup (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34395:19)
    at handlePlugins ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:21)
    at buildOrServeImpl ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:942:5)
    at Object.buildOrServe ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:750:5)
    at $HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2087:17
    at new Promise (<anonymous>)
    at Object.build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2086:14)
    at build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1933:51)
    at runOptimizeDeps (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:41510:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/.pnpm/@nicolasflamel+secp256k1-zkp@0.0.15_fvyp5h33mdlmlhalc4xfh32q7e/node_modules/@nicolasflamel/secp256k1-zkp/index.js:8:29:
      8 │   module["exports"] = require("@nicolasflamel/secp256k1-zkp-react");
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/ed25519-react". The package may have incorrect main/module/exports specified in its package.json.

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21:
      1327 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
    at resolvePackageEntry (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34097:5)
    at tryNodeResolve (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
    at Context.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33598:28)
    at Object.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40156:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62481:21
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34415:34
    at async requestCallbacks.on-resolve ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:22)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:20:
      1251 │       let promise = setup({
           ╵                     ^

    at setup (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34395:19)
    at handlePlugins ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:21)
    at buildOrServeImpl ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:942:5)
    at Object.buildOrServe ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:750:5)
    at $HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2087:17
    at new Promise (<anonymous>)
    at Object.build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2086:14)
    at build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1933:51)
    at runOptimizeDeps (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:41510:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/.pnpm/@nicolasflamel+ed25519@0.0.5_fvyp5h33mdlmlhalc4xfh32q7e/node_modules/@nicolasflamel/ed25519/index.js:8:29:
      8 │   module["exports"] = require("@nicolasflamel/ed25519-react");
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/smaz-react". The package may have incorrect main/module/exports specified in its package.json.

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21:
      1327 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
    at resolvePackageEntry (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34097:5)
    at tryNodeResolve (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
    at Context.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33598:28)
    at Object.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40156:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62481:21
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34415:34
    at async requestCallbacks.on-resolve ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:22)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:20:
      1251 │       let promise = setup({
           ╵                     ^

    at setup (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34395:19)
    at handlePlugins ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:21)
    at buildOrServeImpl ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:942:5)
    at Object.buildOrServe ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:750:5)
    at $HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2087:17
    at new Promise (<anonymous>)
    at Object.build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2086:14)
    at build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1933:51)
    at runOptimizeDeps (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:41510:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/.pnpm/@nicolasflamel+smaz@0.0.7_fvyp5h33mdlmlhalc4xfh32q7e/node_modules/@nicolasflamel/smaz/index.js:8:29:
      8 │   module["exports"] = require("@nicolasflamel/smaz-react");
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/x25519-react". The package may have incorrect main/module/exports specified in its package.json.

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21:
      1327 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
    at resolvePackageEntry (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34097:5)
    at tryNodeResolve (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
    at Context.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33598:28)
    at Object.resolveId (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40156:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62481:21
    at async file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34415:34
    at async requestCallbacks.on-resolve ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:22)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:20:
      1251 │       let promise = setup({
           ╵                     ^

    at setup (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34395:19)
    at handlePlugins ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1251:21)
    at buildOrServeImpl ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:942:5)
    at Object.buildOrServe ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:750:5)
    at $HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2087:17
    at new Promise (<anonymous>)
    at Object.build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:2086:14)
    at build ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1933:51)
    at runOptimizeDeps (file://$HOME/ledger-live/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:41510:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    ../../node_modules/.pnpm/@nicolasflamel+x25519@0.0.4_fvyp5h33mdlmlhalc4xfh32q7e/node_modules/@nicolasflamel/x25519/index.js:8:29:
      8 │   module["exports"] = require("@nicolasflamel/x25519-react");
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "rlp"

    ../../node_modules/.pnpm/@celo+utils@3.0.1/node_modules/@celo/utils/lib/istanbul.js:32:31:
      32 │ var rlp = __importStar(require("rlp"));
         ╵                                ~~~~~

  You can mark the path "rlp" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

2:50:28 PM [vite] error while updating dependencies:
Error: Build failed with 5 errors:
../../node_modules/.pnpm/@celo+utils@3.0.1/node_modules/@celo/utils/lib/istanbul.js:32:31: ERROR: Could not resolve "rlp"
../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/ed25519-react". The package may have incorrect main/module/exports specified in its package.json.
../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/secp256k1-zkp-react". The package may have incorrect main/module/exports specified in its package.json.
../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/smaz-react". The package may have incorrect main/module/exports specified in its package.json.
../../node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1327:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "@nicolasflamel/x25519-react". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1566:15)
    at $HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1024:28
    at runOnEndCallbacks ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1438:61)
    at buildResponseToResult ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1022:7)
    at $HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout ($HOME/ledger-live/node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
```

**Comment by who-biz** [comment]
Actual directory path has been replaced by `$HOME` to mask directory structure on my computer.
